#ifndef __SYSTEM_FIRMWARE_DEVICETREE_PRIVATE_CONFIG_H
#define __SYSTEM_FIRMWARE_DEVICETREE_PRIVATE_CONFIG_H


#if __SYSTEM_FIRMWARE_DEVICETREE_BUILD_SHARED
#  define __SYSTEM_FIRMWARE_DEVICETREE_EXPORT   [[gnu::visibility("protected")]]
#else
#  define __SYSTEM_FIRMWARE_DEVICETREE_EXPORT   /**/
#endif

#define __SYSTEM_FIRMWARE_DEVICETREE_SYMBOL_(x) asm("System.Firmware.DeviceTree." #x)
#define __SYSTEM_FIRMWARE_DEVICETREE_SYMBOL(x)  __SYSTEM_FIRMWARE_DEVICETREE_SYMBOL_(x)



#endif /* ifndef __SYSTEM_FIRMWARE_DEVICETREE_PRIVATE_CONFIG_H */
