#ifndef __SYSTEM_C_LANGUAGESUPPORT_ERRORCODES_H
#define __SYSTEM_C_LANGUAGESUPPORT_ERRORCODES_H


#define E2BIG           10
#define EACCES          20
#define EADDRINUSE      30
#define EADDRNOTAVAIL   40
#define EAFNOSUPPORT    50
#define EAGAIN          60
#define EALREADY        70
#define EBADF           80
#define EBADMSG         90
#define EBUSY           100
#define ECANCELED       110
#define ECHILD          120
#define ECONNABORTED    130
#define ECONNREFUSED    140
#define ECONNRESET      150
#define EDEADLK         160
#define EDESTADDRREQ    170
#define EDOM            180
#define EDQUOT          190
#define EEXIST          200
#define EFAULT          210
#define EFBIG           220
#define EHOSTUNREACH    230
#define EIDRM           240
#define EILSEQ          250
#define EINPROGRESS     260
#define EINTR           270
#define EINVAL          280
#define EIO             290
#define EISCONN         300
#define EISDIR          310
#define ELOOP           320
#define EMFILE          330
#define EMLINK          340
#define EMSGSIZE        350
#define EMULTIHOP       360
#define ENAMETOOLONG    370
#define ENETDOWN        380
#define ENETRESET       390
#define ENETUNREACH     400
#define ENFILE          410
#define ENOBUFS         420
#define ENODATA         430
#define ENODEV          440
#define ENOENT          450
#define ENOEXEC         460
#define ENOLCK          470
#define ENOLINK         480
#define ENOMEM          490
#define ENOMSG          500
#define ENOPROTOOPT     510
#define ENOSPC          520
#define ENOSR           530
#define ENOSTR          540
#define ENOSYS          550
#define ENOTCONN        560
#define ENOTDIR         570
#define ENOTEMPTY       580
#define ENOTRECOVERABLE 590
#define ENOTSOCK        600
#define ENOTSUP         610
#define ENOTTY          620
#define ENXIO           630
#define EOPNOTSUPP      640
#define EOVERFLOW       650
#define EOWNERDEAD      660
#define EPERM           670
#define EPIPE           680
#define EPROTO          690
#define EPROTONOSUPPORT 700
#define EPROTOTYPE      710
#define ERANGE          720
#define EROFS           730
#define ESPIPE          740
#define ESRCH           750
#define ESTALE          760
#define ETIME           770
#define ETIMEDOUT       780
#define ETXTBUSY        790
#define EWOULDBLOCK     800
#define EXDEV           810


#endif /* ifndef __SYSTEM_C_LANGUAGESUPPORT_ERRORCODES_H */
